name: PdxExplorers
main: com.gmail.emertens.PdxExplorers.PdxExplorers
version: 1.10
description: Separate the explorers from the rest. 
authors: [emertens]

commands:
  explorers:
    description: List and manage current explorers
    usage: /<command>

permissions:
  explorers.*:
    description: All explorers commands
    children:
    - explorers.create
    - explorers.delete
    - explorers.revoke
    - explorers.rewards
    - explorers.give
    - explorers.assign
  explorers.create:
    description: Create explorer signs regardless of ownership
    default: op
  explorers.delete:
    description: Delete any route
    default: op
  explorers.revoke:
    description: Revoke a winner
    default: op
  explorers.give:
    description: Reassign ownership of any route
    default: op
  explorers.rewards:
    description: Assign rewards to a route
    default: op
  explorers.assign:
    description: Manually assign a player to a route
    default: op
  explorers.fly:
    description: Modify fly speed
    default: op
